apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resume-screener-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resume-screener
  
  minReplicas: 2      # Minimum pods (always running)
  maxReplicas: 10     # Maximum pods when heavily loaded
  
  metrics:
  # Scale based on CPU usage
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale up when CPU > 70%
  
  # Scale based on memory usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale up when memory > 80%
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      policies:
      - type: Percent
        value: 50                       # Remove 50% of pods at a time
        periodSeconds: 60
    
    scaleUp:
      stabilizationWindowSeconds: 0    # Scale up immediately
      policies:
      - type: Percent
        value: 100                      # Double the pods
        periodSeconds: 30
